shallow_clone: true

version: 0.0.0.alpha2.{build}

image: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

#cache:
#  - foldername -> dependencyfile #caches foldername, but will ignore/update cache if dependencyfile changes
#  surround entire line with single-quotes to make env variable substitution work

install:

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DBOOST_INSTALL_PATH=C:/libraries/boost_1_63_0
  - cd ..

build:
  project: build/GridDyn.sln
  parallel: true
  verbosity: minimal

after_build:

test_script:
  - cd build
  # For controlling which tests get run:
  # ctest -I <start>,<end>,<stride>,<list of test numbers>

artifacts:
